// Exercise 32.1 driver — calls your hand-written arm64 max2 from ex1_max2.s
// Build & run with `make ex1`. Do not edit this file; edit ex1_max2.s.

#include <stdio.h>

long max2(long a, long b);  // defined in ex1_max2.s

int main(void) {
    printf("max2(3, 7)   = %ld  (expected 7)\n", max2(3, 7));
    printf("max2(9, 2)   = %ld  (expected 9)\n", max2(9, 2));
    printf("max2(-5, -1) = %ld  (expected -1)\n", max2(-5, -1));
    printf("max2(4, 4)   = %ld  (expected 4)\n", max2(4, 4));
    return 0;
}
